apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gitops-app
spec:
  template:
    spec:
      containers:
        - name: ai-gitops-app
          env:
            - name: ENVIRONMENT
              value: "prod"
