apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gitops-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: ai-gitops-app }
  template:
    metadata:
      labels: { app: ai-gitops-app }
    spec:
      containers:
        - name: ai-gitops-app
          image: docker.io/vijaynaik1117/ai-with-gitops:v2
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v2"
            - name: ENVIRONMENT
              value: "REPLACED_BY_OVERLAY"
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
